"""Player nickname mappings for fuzzy search.

Data-only module — no logic.
"""

NICKNAMES: dict[str, str] = {
    # Common nicknames used in FPL community
    "kdb": "kevin de bruyne",
    "vvd": "virgil van dijk",
    "taa": "trent alexander-arnold",
    "trent": "trent alexander-arnold",
    "mo salah": "mohamed salah",
    "salah": "mohamed salah",
    "son": "heung-min son",
    "heung min son": "heung-min son",
    "rashford": "marcus rashford",
    "bruno": "bruno fernandes",
    "fernandes": "bruno fernandes",
    "saka": "bukayo saka",
    "foden": "phil foden",
    "palmer": "cole palmer",
    "odes": "martin odegaard",
    "odegaard": "martin odegaard",
    "haaland": "erling haaland",
    "erling": "erling haaland",
    "doku": "jeremy doku",
    "gordon": "anthony gordon",
    "watkins": "ollie watkins",
    "bowen": "jarrod bowen",
    "mitoma": "kaoru mitoma",
    "mbeumo": "bryan mbeumo",
    "isak": "alexander isak",
    "cucurella": "marc cucurella",
    "march": "solomon march",
    "estupinan": "pervis estupinan",
    "dunk": "lewis dunk",
    "ederson": "ederson moraes",
    "diaz": "luis diaz",
    "jota": "diogo jota",
    "gakpo": "cody gakpo",
    "szobo": "dominik szoboszlai",
    "szoboszlai": "dominik szoboszlai",
    "mac allister": "alexis mac allister",
    "macca": "alexis mac allister",
    "conor": "conor gallagher",
    "gallagher": "conor gallagher",
    "jack": "jack grealish",
    "grealish": "jack grealish",
    "rodri": "rodrigo hernandez",
    "stones": "john stones",
    "walker": "kyle walker",
    "dias": "ruben dias",
    "gvardiol": "josko gvardiol",
    "rico": "rico lewis",
    "maddison": "james maddison",
    "richarlison": "richarlison de andrade",
    "kulusevski": "dejan kulusevski",
    "porro": "pedro porro",
    "romero": "cristian romero",
    "vicario": "guglielmo vicario",
    "sonny": "heung-min son",
    "ugarte": "manuel ugarte",
    "mainoo": "kobbie mainoo",
    "martinez": "lisandro martinez",
    "dalot": "diogo dalot",
    "shaw": "luke shaw",
    "onana": "andre onana",
    "garnacho": "alejandro garnacho",
    "hojlund": "rasmus hojlund",
    "zirkzee": "joshua zirkzee",
    "alexander-arnold": "trent alexander-arnold",
}
